name: CD Development

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Intall Entity Framework
      run: dotnet tool install --global dotnet-ef

    - name: Restore dependencies and tools
      run: dotnet restore

    - name: Apply Database Migrations
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING_DEV }}
      run: dotnet ef database update --project MvcBootstrap.App

  deploy:
    needs: migrate
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Copy Dockerfile
        run: cp MvcBootstrap.App/Dockerfile .
      
      - name: Install fly cli
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy to fly
        run: /home/runner/.fly/bin/flyctl -t ${{ secrets.FLY_TOKEN_DEV }} deploy -c fly.development.toml
